#!/bin/bash
# Google Sitemap 提交脚本
# 用法: bash submit-sitemap.sh

echo "📤 Sitemap 提交指南"
echo "=================="
echo ""
echo "✅ Sitemap URL:"
echo "https://rent-vs-buy-calculator.it.com/sitemap.xml"
echo ""
echo "💡 推荐提交方法:"
echo ""
echo "方法1：Google Search Console (官方推荐)"
echo "-------------------------------------------"
echo "1. 登录: https://search.google.com/search-console"
echo "2. 选择您的网站资源"
echo "3. 左侧菜单: 索引 → 站点地图"
echo "4. 输入Sitemap URL并点击提交"
echo "   https://rent-vs-buy-calculator.it.com/sitemap.xml"
echo "5. 或使用快速链接:"
echo "   https://search.google.com/search-console/sitemap-feed"
echo ""
echo "方法2：其他搜索引擎提交"
echo "-------------------------------------------"
echo ""
echo "Bing Webmaster:"
echo "  https://www.bing.com/webmasters"
echo ""
echo "Yandex Webmaster:"
echo "  https://webmaster.yandex.com"
echo ""
echo "注意：DuckDuckGo会自动发现，无需手动提交"
echo ""
echo "⏱ 预期时间线:"
echo "  • Google发现页面: 1-3天"
echo "  • 开始索引处理: 3-7天"
echo "  • 完全收录: 1-2周"
echo ""
echo "🔍 检查索引状态:"
echo "  https://search.google.com/search-console"
echo "  使用'网址检查'功能查看Austin页面状态"
echo ""
